#!/bin/sh
set -e

file_exists_or_abort()
{
    filename=$1
    if [ ! -f $filename ]
    then
	echo "File '$filename' not found. Did you execute this script in the directory in which it's stored?"
	exit 2
    fi
}

file_exists_or_abort mylib.cvl

sourcefile=WG.25519.m4.cv
file_exists_or_abort $sourcefile
for sessions in AB AB-BA
do
    pattern=WG.25519.$sessions
    for replay_status in no_replay_prot replay_prot
    do

	# The following is for correspondences on the second, third, and
	# the transport data messages, message secrecy, and absence of unknown
	# key share attacks.
	for icompr in S_i_compr E_i_compr
	do
	    for rcompr in S_r_compr E_r_compr
	    do
		modname=$pattern.$icompr.$rcompr.$replay_status
		m4 --define="m4_name=$modname" -Dm4_zero_test -Dm4_$icompr -Dm4_$rcompr -Dm4_$sessions -Dm4_$replay_status $sourcefile > $modname.cv
	    done
	done
	
    done
done
