#!/bin/sh

if [ -x ./xtime ]
then
    PROG=./xtime
else
    PROG=
fi

for i in otway-rees2Stream otway-rees2StreamTag otway-rees3Stream otway-rees3StreamTag otway-rees2Block otway-rees2BlockTag otway-rees3Block otway-rees3BlockTag yahalom3Stream yahalom3StreamMod yahalom3StreamMac needham-schroeder-sk3Stream needham-schroeder-skcorr3Stream needham-schroeder-skcorr3StreamAuth2 fdh fdh-JSC pfdh woolamsk woolamskcorr woolamskcorr_tbl denning-sacco3Block denning-sacco-corr3Block needham-schroeder-pk3Block needham-schroeder-pk3BlockHash needham-schroeder-pkcorr3Block needham-schroeder-pkcorr3BlockHash needham-schroeder-pk3BlockAuth needham-schroeder-pkcorr3BlockAuth encryptBR93-1 woolampk woolampkcorr woolamskcorrBlock encryptBR93-2v denning-sacco-corr3Block-auto needham-schroeder-pkcorr3BlockHash-auto wmf-tagged wmf-tagged-payload signedDH signedDH-DDH signedDH-forward-secrecy
do
	echo PROTOCOL $i
	$PROG ./cryptoverif examples/$i.cv > tmp.out 2>&1
	egrep \(PROTOCOL\|'RESULT Could not prove'\|'All queries proved'\|xtime\|Error\|user\) tmp.out > tmp.res
	echo >> examples/$i.cv
	echo '(* EXPECTED' >> examples/$i.cv
	cat tmp.res >> examples/$i.cv
	echo 'END *)' >> examples/$i.cv
done

for i in otway-rees3Stream yahalom3Stream yahalom3StreamMod yahalom3StreamMac needham-schroeder-sk3Stream needham-schroeder-sk3StreamAuth needham-schroeder-sk3StreamFull needham-schroeder-skcorr3Stream needham-schroeder-skcorr3StreamAuth needham-schroeder-skcorr3StreamFull woolamsk woolamskcorr denning-sacco3Block denning-sacco-corr3Block needham-schroeder-pk3BlockAuth needham-schroeder-pkcorr3BlockAuth needham-schroeder-pkcorr3BlockKeyNa needham-schroeder-pkcorr3BlockKeyNb needham-schroeder-pkcorr3BlockKeyHash woolampk woolampkcorr woolampkWeaksign woolampkWeaksign-corr woolamskcorrBlock
do
	echo PROTOCOL $i
	$PROG ./cryptoverif authexamples/$i.cv > tmp.out 2>&1
	egrep \(PROTOCOL\|'RESULT Could not prove'\|'All queries proved'\|xtime\|Error\|user\) tmp.out > tmp.res
	echo >> authexamples/$i.cv
	echo '(* EXPECTED' >> authexamples/$i.cv
	cat tmp.res >> authexamples/$i.cv
	echo 'END *)' >> authexamples/$i.cv
done

for i in fdh.ocv fdh-JSC.ocv encryptBR93-1.ocv encryptBR93-2v.ocv signedDH.ocv  signedDH-DDH.ocv OEKE.ocv
do
    echo PROTOCOL $i
    $PROG ./cryptoverif -in oracles oexamples/$i > tmp.out 2>&1
    egrep \(PROTOCOL\|'RESULT Could not prove'\|'All queries proved'\|xtime\|Error\|user\) tmp.out > tmp.res
	echo >> ./oexamples/$i
	echo '(* EXPECTED' >> oexamples/$i
	cat tmp.res >> oexamples/$i
	echo 'END *)' >> oexamples/$i
done

for i in ../../dev/cnrs/webperso/cryptoverif/kerberos/*.cv
do
	echo PROTOCOL $i
	$PROG ./cryptoverif $i > tmp.out 2>&1
    egrep \(PROTOCOL\|'RESULT Could not prove'\|'All queries proved'\|xtime\|Error\|user\) tmp.out > tmp.res
	echo >> $i
	echo '(* EXPECTED' >> $i
	cat tmp.res >> $i
	echo 'END *)' >> $i
done

for i in examplesnd/test/* examplesnd/kerberos/* examplesnd/implem/*
do
    if [ -f $i ]
    then
	echo PROTOCOL $i
	$PROG ./cryptoverif $i > tmp.out 2>&1
	egrep \(PROTOCOL\|'RESULT Could not prove'\|'All queries proved'\|xtime\|Error\|user\) tmp.out > tmp.res
	echo >> $i
	echo '(* EXPECTED' >> $i
	cat tmp.res >> $i
	echo 'END *)' >> $i
    fi
done

for i in examplesnd/otest/*
do
    if [ -f $i ]
    then
	echo PROTOCOL $i
	$PROG ./cryptoverif -in oracles $i > tmp.out 2>&1
	egrep \(PROTOCOL\|'RESULT Could not prove'\|'All queries proved'\|xtime\|Error\|user\) tmp.out > tmp.res
	echo >> $i
	echo '(* EXPECTED' >> $i
	cat tmp.res >> $i
	echo 'END *)' >> $i
    fi
done
