#!/bin/sh

if [ -x ./xtime ]
then
    PROG=./xtime
else
    PROG=
fi

for k in key_AK key_SK
do
    for loc in loc1 loc2 loc3
    do
	m4 -D$k -D$loc examples/kerberos/BasicKerberos_keyuse_Updated.m4.cv > examples/kerberos/BasicKerberos_keyuse.$k.$loc.cv
	m4 -D$k -D$loc examples/kerberos/PublicKeyKerberos_keyuse_Updated.m4.cv > examples/kerberos/PublicKeyKerberos_keyuse.$k.$loc.cv
    done
done

for key in IVCC IVSC EKCC EKSC MKCC MKSC
do
    m4 -DONEKEY=$key implementation/ssh/ssh-secrecy-key.m4.ocv > implementation/ssh/ssh-secrecy-key-$key.ocv
done
m4 implementation/ssh/ssh-secrecy-key.m4.ocv > implementation/ssh/ssh-secrecy-key.ocv


for i in examples/basic/*.pcv examples/basic/*.cv examples/obasic/*.ocv examples/kerberos/*.pcv examples/kerberos/*.cv examplesnd/test/* examplesnd/proverif/*.pcv implementation/wlsk/woolamskcorr_tbl.cv
do
    if [ -f $i ]
    then
	case $i in
	    *.m4.cv) ;;
	    *)	echo PROTOCOL $i
		$PROG ./cryptoverif $i > tmp.out 2>&1
		egrep \(PROTOCOL\|'RESULT Could not prove'\|'All queries proved'\|xtime\|Error\|user\) tmp.out > tmp.res
		echo >> $i
		echo '(* EXPECTED' >> $i
		cat tmp.res >> $i
		echo 'END *)' >> $i
	esac
    fi
done

for i in examplesnd/otest/* implementation/nspk/nspk3tbl.ocv implementation/ssh/ssh.ocv implementation/ssh/ssh-secrecy-key-*.ocv
do
    if [ -f $i ]
    then
	echo PROTOCOL $i
	$PROG ./cryptoverif -in oracles $i > tmp.out 2>&1
	egrep \(PROTOCOL\|'RESULT Could not prove'\|'All queries proved'\|xtime\|Error\|user\) tmp.out > tmp.res
	echo >> $i
	echo '(* EXPECTED' >> $i
	cat tmp.res >> $i
	echo 'END *)' >> $i
    fi
done

