#!/bin/bash

if [ -x ./xtime ]
then
    PROG=../xtime
else
    PROG=
fi

CRYPTOVERIF="$HOME/tmp/cryptoverif1.28/cryptoverif -lib $HOME/tmp/cryptoverif1.28/default"
CRYPTOVERIFTLS="$HOME/tmp/cryptoverif1.28/cryptoverif -lib tls-2017SP/tls-lib"

# The arguments of analyze are
# $1 = protocol name
# $2 = CryptoVerif program

function analyze()
{
    echo -n PROTOCOL $1 " "
    $PROG $2 $1 > tmp.out 2>&1
    egrep \(PROTOCOL\|'RESULT Could not prove'\|'All queries proved'\|xtime\|Error\|user\) tmp.out > tmp.res
    awk '/EXPECTED/, /END/ { print $0; }' ../examples-1.28-converted/$1 | grep -v EXPECTED | grep -v END > tmp.old
    grep -v user tmp.old > tmp.oldres
    grep -v user tmp.res > tmp.actualres
    if diff -q -b tmp.oldres tmp.actualres >/dev/null
    then 
	echo OK
	# I am still replacing the result to update the runtime
	awk 'BEGIN { out=1; } /EXPECTED/ { out=0; } { if (out==1) { print $0; } }' ../examples-1.28-converted/$1 > tmp.resremoved
	echo '(* EXPECTED' >> tmp.resremoved
	cat tmp.res >> tmp.resremoved
	echo 'END *)' >> tmp.resremoved
	mv tmp.resremoved ../examples-1.28-converted/$1
    else
	if grep -q 'RESULT Could not prove' tmp.actualres
	then
	    echo Replacing result
	    awk 'BEGIN { out=1; } /EXPECTED/ { out=0; } { if (out==1) { print $0; } }' ../examples-1.28-converted/$1 > tmp.resremoved
	    echo '(* EXPECTED' >> tmp.resremoved
	    cat tmp.res >> tmp.resremoved
	    echo 'END *)' >> tmp.resremoved
	    mv tmp.resremoved ../examples-1.28-converted/$1
	else
	    echo WARNING: Different error messages
	    echo Old
	    cat tmp.oldres
	    echo New
	    cat tmp.actualres
	fi
    fi
}

cd examples-1.28

for i in basic/*.cv authbasic/*.cv obasic/*.ocv kerberos/*.cv nd/test/*.cv nd/kerberos/*.cv nd/implem/*.cv nd/arinc823/*.cv implementation/*.cv nd/otest/*.ocv nd/implem/*.ocv nd/arinc823/*.ocv implementation/*.ocv
do
    analyze $i "$CRYPTOVERIF"
done

cat  $HOME/tmp/cryptoverif1.28/default.cvl tls-2017SP/tls-primitives.cvl > tls-2017SP/tls-lib.cvl

for i in tls-2017SP/*.cv
do
    analyze $i "$CRYPTOVERIFTLS"
done

cd ..
