#!/bin/bash

if [ -x ./xtime ]
then
    PROG=./xtime
else
    PROG=
fi

# The arguments of analyze are
# $1 = protocol name
# $2 = CryptoVerif options
# $3 = input filename (wrt the CryptoVerif directory)
# $4 = output filename (wrt the CryptoVerif directory)

function analyze()
{
	echo -n PROTOCOL $1 " "
	$PROG ./cryptoverif $2 $3 > tmp.out 2>&1 
	echo PROTOCOL $1 >> $4
	cat tmp.out >> $4
	egrep \(PROTOCOL\|'RESULT Could not prove'\|'All queries proved'\|xtime\|Error\|user\) tmp.out > tmp.res 
	awk '/EXPECTED/, /END/ { print $0; }' $3 | grep -v EXPECTED | grep -v END > tmp.expected
	grep -v user tmp.expected > tmp.expectedres
	grep -v user tmp.res > tmp.actualres
	if diff -q -b tmp.expectedres tmp.actualres >/dev/null
	then 
	    echo OK
	else
	    echo
	    echo RESULTS DIFFER! Expected:
	    cat  tmp.expectedres
	    echo Actual:
	    cat tmp.actualres
	fi
	(echo -n "EXPECTED: "; grep user tmp.expected ; echo -n "ACTUAL: "; grep user tmp.res) | awk '/^EXPECTED:/ { expectedtime = substr($2, 0, length($2)-1); } /^ACTUAL:/ { actualtime = substr($2, 0, length($2)-1); } END { if (actualtime != "") { if (actualtime + 0 > expectedtime * 1.2 + 0.2) { print "Slower: old=" expectedtime " new=" actualtime}; if (actualtime + 0 < expectedtime * 0.8 - 0.2) { print "Faster: old=" expectedtime " new=" actualtime; } } }'
}

mkdir -p tests

echo
echo TEST
echo
output=test`date '+%Y.%m.%d-%H_%M_%S'`
(
for i in examples/*.cv
do
	analyze $i "" $i tests/$output
done
) | tee tests/res-$output
egrep \(PROTOCOL\|'RESULT Could not prove'\|'All queries proved'\|xtime\|Error\|user\) tests/$output > tests/sum-$output


echo
echo AUTHTEST
echo
output=auth`date '+%Y.%m.%d-%H_%M_%S'`
(for i in authexamples/*.cv
do
	analyze $i "" $i tests/$output
done
) | tee tests/res-$output
egrep \(PROTOCOL\|'RESULT Could not prove'\|'All queries proved'\|xtime\|Error\|user\) tests/$output > tests/sum-$output


echo
echo OTEST
echo
output=otest`date '+%Y.%m.%d-%H_%M_%S'`
(
for i in oexamples/*.ocv
do
    analyze $i "-in oracles" $i tests/$output
done
) | tee tests/res-$output
egrep \(PROTOCOL\|'RESULT Could not prove'\|'All queries proved'\|xtime\|Error\|user\) tests/$output > tests/sum-$output


if [ -d ../../dev/web/webperso/cryptoverif/kerberos ]
then
echo
echo WEB
echo
output=web`date '+%Y.%m.%d-%H_%M_%S'`
(
for i in ../../dev/web/webperso/cryptoverif/kerberos/*.cv
do
	analyze $i "" $i tests/$output
done
) | tee tests/res-$output
egrep \(PROTOCOL\|'RESULT Could not prove'\|'All queries proved'\|xtime\|Error\|user\) tests/$output > tests/sum-$output
fi


if [ -d examplesnd ]
then
echo
echo NDTEST
echo
output=ndtest`date '+%Y.%m.%d-%H_%M_%S'`
rm examplesnd/*/*~ 
(
echo
echo CHANNELS FRONTEND
echo

for i in examplesnd/test/* examplesnd/kerberos/* examplesnd/implem/*.cv examplesnd/arinc823/*.cv implementation/wlsk/woolamskcorr_tbl.cv
do
    if [ -f $i ]
    then
	analyze $i "" $i tests/$output
    fi
done

echo
echo ORACLES FRONTEND
echo

for i in examplesnd/otest/* examplesnd/implem/*.ocv examplesnd/arinc823/*.ocv implementation/nspk/nspk3tbl.ocv implementation/ssh/ssh.ocv implementation/ssh/ssh-secrecy-key-*.ocv
do
    if [ -f $i ]
    then
	analyze $i "-in oracles" $i tests/$output
    fi
done
) | tee tests/res-$output
egrep \(PROTOCOL\|'RESULT Could not prove'\|'All queries proved'\|xtime\|Error\|user\) tests/$output > tests/sum-$output
fi

rm tmp.*
