#!/bin/sh

set -e

SRC="parsing_helper.mli parsing_helper.ml occ_map.mli occ_map.ml types.ml ptree.mli settings.mli settings.ml parser.mli parser.ml lexer.ml terms.mli terms.ml array_ref.mli array_ref.ml incompatible.mli incompatible.ml info_from_term.mli info_from_term.ml def.mli def.ml match_eq.mli match_eq.ml stringmap.mli stringmap.ml polynom.mli polynom.ml display.mli display.ml  syntax.mli syntax.ml displaytex.mli displaytex.ml check.mli check.ml computeruntime.mli computeruntime.ml ../srcnd/probatest.ml"

cd src

ocamlyacc -v parser.mly
ocamllex lexer.mll

case X$1 in
    Xnative | X )
	ocamlopt -o ../srcnd/probatest unix.cmxa str.cmxa $SRC;;
    Xdebug )
	ocamlc -g -o ../srcnd/probatest unix.cma str.cma $SRC;;
    *)
	echo Unknown option
esac

cd ..

