#!/bin/sh

VERSION=$1
YEAR=`date +%Y`
DEST=$HOME/cryptoverifreleases
DESTD=$DEST/cryptoverif$VERSION

echo Creating release of CryptoVerif version $VERSION

if [ -d $DEST ]
then
        echo
else
        echo Directory $DEST does not exist. Please create it.
        exit 2
fi

if [ -d $DESTD ]
then
        echo Directory $DESTD already exists. Please remove it.
        exit 2
fi

cd ..
mkdir $DESTD

sed s/VERSION/$VERSION/g\;s/YEAR/$YEAR/g README > $DESTD/README
cp CHANGES LICENSE build build.bat test $DESTD

mkdir $DESTD/cryptolib $DESTD/docs $DESTD/examples $DESTD/examples/basic $DESTD/examples/obasic $DESTD/examples/kerberos $DESTD/examples/arinc823 $DESTD/examples/arinc823/sharedkey $DESTD/examples/arinc823/publickey $DESTD/examples/textsecure $DESTD/examples/tls13 $DESTD/examples/wireguard $DESTD/src $DESTD/tests $DESTD/emacs $DESTD/implementation $DESTD/implementation/nspk $DESTD/implementation/wlsk $DESTD/implementation/ssh

rm *~ */*~ */*/*~

cd docs
pdflatex manual.tex
bibtex manual
pdflatex manual.tex
pdflatex manual.tex
cd ..

cp docs/manual.pdf $DESTD/docs
cp emacs/* $DESTD/emacs
cp implementation/nspk/README $DESTD/implementation/nspk
cp implementation/wlsk/README $DESTD/implementation/wlsk
cp implementation/ssh/README $DESTD/implementation/ssh
cp implementation/nspk/build.sh $DESTD/implementation/nspk
cp implementation/wlsk/build.sh $DESTD/implementation/wlsk
cp implementation/ssh/build.sh $DESTD/implementation/ssh
cp examples/arinc823/gen $DESTD/examples/arinc823
cp examples/kerberos/*.pcv examples/kerberos/*.m4.cv $DESTD/examples/kerberos
cp examples/textsecure/runcv $DESTD/examples/textsecure
cp examples/tls13/runcv examples/tls13/README.md $DESTD/examples/tls13
cp examples/wireguard/boolean_choice.cvl examples/wireguard/hashgen.ml examples/wireguard/preamble.cvl examples/wireguard/runWG.25519 examples/wireguard/separator.cvl examples/wireguard/WG.25519.dos.cv examples/wireguard/*.m4.cv $DESTD/examples/wireguard

for i in src/*.ml src/*.mli src/*.mll implementation/base.ml* implementation/crypto*.ml* implementation/nspk/A*.ml implementation/nspk/B*.ml implementation/nspk/S*.ml  implementation/nspk/test.ml implementation/nspk/nspk3tbl.ocv implementation/wlsk/init.ml implementation/wlsk/keygen.ml implementation/wlsk/resp.ml implementation/wlsk/server.ml implementation/wlsk/test_wlsk.ml implementation/wlsk/woolamskcorr_tbl.cv implementation/ssh/ssh*.ml* implementation/ssh/add_key.ml implementation/ssh/ssh*.ocv examples/basic/* examples/obasic/* examples/arinc823/arinc823prim.cvl examples/arinc823/*/*.m4.cv examples/arinc823/*/*.ocv examples/textsecure/*.m4.cv examples/tls13/*.cv* cryptolib/cryptogen.ml cryptolib/commonlib.cvl cryptolib/crypto.pvl cryptolib/*.ocv 
do
        if [ -f $i ]
        then
                cat distrib/head.ml $i > $DESTD/$i
        fi
done
for i in src/*.mly 
do
        if [ -f $i ]
        then
                (echo "%{"; cat distrib/head.ml; echo "%}"; cat $i) > $DESTD/$i
        fi
done

(cat distrib/head.ml;echo "let version = \""$VERSION\") > $DESTD/src/version.ml

cp $DESTD/implementation/crypto_real.ml $DESTD/implementation/crypto.ml

rm $DESTD/src/*lexer.ml $DESTD/src/*parser.ml $DESTD/src/*parser.mli $DESTD/src/profile.ml* 

cd $DEST
tar -czf $DEST/cryptoverif$VERSION.tar.gz cryptoverif$VERSION
rm -r $DESTD

