#!/bin/sh
set -e

file_exists_or_abort()
{
    filename=$1
    if [ ! -f $filename ]
    then
	echo "File '$filename' not found. Did you execute this script in the directory in which it's stored?"
	exit 2
    fi
}

if [ -f ../wireguard/hashgen.ml ]
then
    cd ../wireguard
    ocamlopt -o hashgen hashgen.ml
    ./hashgen 1 10 > hashoracles.cvl
    file_exists_or_abort preamble.cvl
    file_exists_or_abort ../../default.cvl
    file_exists_or_abort separator.cvl
    file_exists_or_abort boolean_choice.cvl
    cat preamble.cvl ../../default.cvl separator.cvl hashoracles.cvl boolean_choice.cvl > ../noiseNK/mylib.cvl
    cd ../noiseNK
fi

file_exists_or_abort mylib.cvl

