#!/bin/bash
set -e

function file_exists_or_abort()
{
    filename=$1
    if [ ! -f $filename ]
    then
	echo "File '$filename' not found. Did you execute this script in the directory in which it's stored?"
	exit 2
    fi
}


dirs=sharedkey
dirp=publickey

file_exists_or_abort ../../default.cvl
file_exists_or_abort arinc823prim.cvl
cat ../../default.cvl arinc823prim.cvl > mylib.cvl

# shared key
for prot in ORIGINAL SINGLE_TU REPLAY_PROT
do
    for prop in SECRECY AUTHENTICATION UKS KEY_SECRECY 
    do
	sourcefile=$dirs/arinc823-secret-key.$prop.m4.cv
	file_exists_or_abort $sourcefile
	m4 -D$prot $sourcefile > $dirs/arinc823-secret-key.$prop.$prot.cv
    done
done

# public key - original protocol
for prot in NOREPLAY_PROT REPLAY_PROT
do
    for prop in SECRECY AUTHENTICATION KEY_SECRECY
    do  
	sourcefile=$dirp/arinc823-public-key.$prop.m4.cv
	file_exists_or_abort $sourcefile
	m4 -D$prot $sourcefile > $dirp/arinc823-public-key.$prop.$prot.cv
    done
done

# public key - fixed protocol
for prot in REPLAY_PROT #NOREPLAY_PROT 
do
    sourcefile=$dirp/arinc823-public-key.fixed.KEY_SECRECY.m4.cv
    file_exists_or_abort $sourcefile
    m4 -D$prot $sourcefile > $dirp/arinc823-public-key.fixed.KEY_SECRECY.$prot.cv

    sourcefile=$dirp/arinc823-public-key.fixed.SECRECY.m4.cv
    file_exists_or_abort $sourcefile
    m4 -D$prot $sourcefile > $dirp/arinc823-public-key.fixed.SECRECY.$prot.cv

    for comp in COMPROMISE_U COMPROMISE_V NO_COMPROMISE
    do 
	sourcefile=$dirp/arinc823-public-key.fixed.AUTHENTICATION.m4.cv
	file_exists_or_abort $sourcefile
	m4 -D$prot -D$comp $sourcefile > $dirp/arinc823-public-key.fixed.AUTHENTICATION.$comp.$prot.cv
    done
done
