#!/bin/sh
set -e

file_exists_or_abort()
{
    filename=$1
    if [ ! -f $filename ]
    then
	echo "File '$filename' not found. Did you execute this script in the directory in which it's stored?"
	exit 2
    fi
}


sourcefile=TextSecure.m4.cv
file_exists_or_abort $sourcefile

for prot in NO_REPLAY_PROT REPLAY_PROT
do
    m4 -D$prot $sourcefile > TextSecure.$prot.cv
done
